import ReduxProvider from "./redux/Provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthModal from "./components/AuthModal";
import Sidebar from "./components/Sidebar";
import MobileMenu from "./components/MobileMenu";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>

      <body>
        
       <ReduxProvider>
        <AuthModal/>
        <MobileMenu/>
    
        
          {children} 
        
          
          </ReduxProvider>

          </body>
    </html>
  );
}
